### ISSUE TITLE
Exporting API Autocomplete wants to do it multiple times.

### ISSUE THREAD

**Issue by HunterAhlquist** [KnowZero/Krita-PythonPluginDeveloperTools#1]
When I go to export the API file, it saves it, but opens the dialog at least 2 more times than it should.

**Comment by KnowZero** [comment]
You probably clicked to manually download the api a few times my guess? I added a fix though so it should be fine now.

**Comment by KnowZero** [comment]
Closing ticket, reopen it if issue persists
